version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: atomic_reader
    env_file:
      - .env.production
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: ghcr.io/tmko16/atomic_reader:latest
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  pg-data:
